// Integration test module declarations

mod android_error_handling_test;
mod android_manager_integration_test;
mod android_parsing_test;
mod app_fixture_test;
pub mod app_lifecycle_frida;
mod app_main_logic_test;
mod app_mod_integration_test;
mod app_realistic_test;
mod app_state_concurrency_test;
mod cache_background_test;
pub mod companion_orchestration;
mod comprehensive_test;
mod device_creation_navigation_test;
mod device_creation_test;
mod device_lifecycle_models_test;
mod device_lifecycle_test;
mod device_operations_test;
mod device_sync_test;
pub mod dual_backend_lifecycle;
mod error_recovery_test;
pub mod host_containment_test;
pub mod image_preparation_test;
mod ios_manager_integration_test;
pub mod kernel_debug_lease;
pub mod legacy_non_regression_test;
mod log_streaming_test;
mod models_test;
mod navigation_circular_test;
mod notification_test;
mod panel_switching_test;
mod platform_switching_test;
pub mod quickstart_scenario_walkthrough_test;
pub mod root_proof_falsification;
pub mod system_daemon_trace_test;
mod ui_focus_theme_test;
mod ui_render_test;
mod utils_command_test;
